"""Generates src/shared/Assets.lua from assets/manifest.json (uploaded image ids) and assets/sounds.json.

Run after uploading new images: python3 tools/gen_assets_lua.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), '..')
man = json.load(open(os.path.join(ROOT, 'assets', 'manifest.json')))
snd_path = os.path.join(ROOT, 'assets', 'sounds.json')
sounds = json.load(open(snd_path)) if os.path.exists(snd_path) else {}


def lua_table(name, d, comment):
    lines = [f'-- {comment}', f'Assets.{name} = {{']
    for k in sorted(d):
        v = d[k]
        if isinstance(v, dict):
            fields = ', '.join(f'{fk} = {json.dumps(fv)}' for fk, fv in v.items())
            lines.append(f'\t{k} = {{ {fields} }},')
        else:
            lines.append(f'\t{k} = "{v}",')
    lines.append('}')
    return '\n'.join(lines)


out = ['-- Party Dash: uploaded asset ids. GENERATED by tools/gen_assets_lua.py from assets/manifest.json and',
       '-- assets/sounds.json. Do not hand-edit; regenerate. FROZEN CONTRACT (keys are stable, ids may change).',
       '-- Icons are glossy cartoon PNGs with transparency (ChatGPT generated, assets/icons/*.png).',
       '-- Textures are seamless 256px grayscale tiles meant to be tinted with Texture.Color3 (tools/gen_textures.py).',
       'local Assets = {}', '']
icons = dict(man.get('icons', {}))
planned = man.get('icons_planned', {})
for key, fb in planned.items():
    if key not in icons and fb in icons:
        icons[key] = icons[fb]  # placeholder until the real icon is generated (same key, never empty)
out.append(lua_table('Icons', icons, 'ImageLabel.Image values (planned keys point at a similar icon until generated)'))
out.append('')
out.append(lua_table('Art', man.get('art', {}), 'larger illustrations (logo, loading background, minigame cards)'))
out.append('')
out.append(lua_table('Textures', man.get('textures', {}), 'Texture.Texture values (tint with Color3)'))
out.append('')
out.append(lua_table('Sounds', sounds, 'Sound ids + default volume (see Shared.Audio)'))
out.append('')
out.append('''-- Returns the icon id or "" when missing (never errors, so a typo shows an empty image instead of crashing UI).
function Assets.icon(name: string): string
	return Assets.Icons[name] or Assets.Art[name] or ""
end

return Assets
''')
open(os.path.join(ROOT, 'src', 'shared', 'Assets.lua'), 'w').write('\n'.join(out))
print('wrote src/shared/Assets.lua')
