"""Convert a JSON file into a Luau ModuleScript returning the same data as a table."""
import json, sys, re

IDENT = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')

def emit(v, ind=0):
    pad = '\t' * (ind + 1)
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if v is None:
        return 'nil'
    if isinstance(v, (int, float)):
        r = repr(round(v, 4)) if isinstance(v, float) else str(v)
        return r[:-2] if r.endswith('.0') else r
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        if all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in v):
            return '{' + ', '.join(emit(x) for x in v) + '}'
        if not v:
            return '{}'
        return '{\n' + ''.join(f'{pad}{emit(x, ind + 1)},\n' for x in v) + '\t' * ind + '}'
    if isinstance(v, dict):
        if not v:
            return '{}'
        parts = []
        for k, x in v.items():
            key = k if IDENT.match(k) else f'[{json.dumps(k)}]'
            parts.append(f'{pad}{key} = {emit(x, ind + 1)},\n')
        return '{\n' + ''.join(parts) + '\t' * ind + '}'
    raise TypeError(type(v))

src, dst, header = sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else ''
data = json.load(open(src))
with open(dst, 'w') as f:
    if header:
        f.write(f'-- {header}\n')
    f.write('-- Generated by tools/json_to_luau.py. Do not edit by hand.\n')
    f.write('return ' + emit(data) + '\n')
